### PR TITLE
Load fonts locally & not from Google

### LINKED ISSUE #47: Do not load fonts from Google
Come on, we want it to work in intranet other places where you don't want it to call to Google. It is also a privacy issue.

So please just include your fonts locally.

### PR DESCRIPTION
**Pull request by rugk**
Fixes #47 

Note that I have not checked the licenses for the fonts, I just used the ones from Google.
You might need to add some licenses to your LICENSE file.

### CODE REVIEW

**Comment by kern** [comment]
Are any other formats than woff2 still necessary? Is woff no longer required in modern browsers (specifically ones supporting WebRTC)?

If you add the proper LICENSE for these, will merge. Thanks!

**Comment by rugk** [comment]
I don't know what fonts should be supported. Maybe a look on how Font Awesome does it would be helpful.

Can you point me to the correct license for these fonts?

**Comment by rugk** [comment]
Okay, so [they](https://fonts.google.com/specimen/Lobster) [both](https://fonts.google.com/specimen/Quicksand) seem to be licensed under the [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web). Is it enough when I add the link?

**Comment by kern** [comment]
If you append the open font license to the LICENSE file and rebase against master, I'll merge! :)

**Comment by mcccs** [comment]
@kern ?

**Pull request merged**
